name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6f49040532606cffe56fb0134da670e47b4b17f67ba751468a9808adbccc938"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
