name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1370828f8739b651f3ab7f61416cddcbefb724d71f80b6716d8dd436ed9d58c7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.10"]
