name = "Queer Minecraft Server Modpack"
author = "arc2-group"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cda5757d3ca8caacc1dd09747b0a53d2e81c47cf60fd249521b0e4bf6ea0630"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
